[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx/error.log
stdout_logfile=/var/log/nginx/access.log
priority=10

[program:easy-strm]
command=/app/easy-strm
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/logs/error.log
stdout_logfile=/app/logs/access.log
environment=SERVER_URL="%(ENV_SERVER_URL)s",JWT_SECRET="%(ENV_JWT_SECRET)s",PG_HOST="%(ENV_PG_HOST)s",PG_PORT="%(ENV_PG_PORT)s",PG_DATABASE="%(ENV_PG_DATABASE)s",PG_USER="%(ENV_PG_USER)s",PG_PASSWORD="%(ENV_PG_PASSWORD)s",REDIS_HOST="%(ENV_REDIS_HOST)s",REDIS_PORT="%(ENV_REDIS_PORT)s",REDIS_PASSWORD="%(ENV_REDIS_PASSWORD)s"
priority=20
